import React, { useState } from 'react';
import { Navigate, useNavigate } from 'react-router-dom';
import { api } from '../lib/api.js';

export default function CreateLesson({ auth }) {
  const navigate = useNavigate();
  const [topic, setTopic] = useState('');
  const [words, setWords] = useState('');
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState(null);

  if (auth === false) return <Navigate to="/403" replace />;

  const handleSubmit = async (e) => {
    e.preventDefault();
    setError(null);
    setLoading(true);
    try {
      const lesson = await api.createLesson({ prompt_topic: topic, prompt_words: words || null });
      navigate(`/lesson/${lesson.hash_id}`);
    } catch (err) {
      if (err.status === 429) {
        setError("You've reached today's limit of 30 lessons. Try again tomorrow.");
      } else {
        setError(err.data?.message || 'Failed to generate the lesson. Please try again.');
      }
      setLoading(false);
    }
  };

  return (
    <section className="flex-grow bg-gradient-to-br from-slate-50 to-slate-200/70 py-12 px-4">
      <div className="max-w-xl mx-auto">
        <div className="mb-8">
          <h1 className="text-3xl font-extrabold text-slate-900 mb-2">Create a Lesson</h1>
          <p className="text-slate-500 text-sm">Describe a topic and optionally list words to practise. The lesson is generated by AI in about 15–20 seconds.</p>
        </div>

        <form
          onSubmit={handleSubmit}
          aria-busy={loading}
          className="bg-white rounded-2xl shadow-sm border border-slate-200 p-6 space-y-5"
        >
          <div>
            <label className="block text-sm font-semibold text-slate-700 mb-1.5" htmlFor="topic">
              Topic <span className="text-slate-400 font-normal">(grammar rule or discussion subject)</span>
            </label>
            <textarea
              id="topic"
              value={topic}
              onChange={e => setTopic(e.target.value)}
              maxLength={500}
              required
              disabled={loading}
              rows={3}
              placeholder="e.g. Present tense conjugation, or Global warming"
              className="w-full rounded-xl border border-slate-200 px-3 py-2.5 text-sm text-slate-800 placeholder-slate-400 focus:outline-none focus:ring-2 focus:ring-sky-500 resize-none disabled:opacity-60 disabled:bg-slate-50"
            />
            <p className="text-right text-xs text-slate-400 mt-1">{topic.length}/500</p>
          </div>

          <div>
            <label className="block text-sm font-semibold text-slate-700 mb-1.5" htmlFor="words">
              Words to practise <span className="text-slate-400 font-normal">(optional — any language)</span>
            </label>
            <textarea
              id="words"
              value={words}
              onChange={e => setWords(e.target.value)}
              maxLength={1000}
              disabled={loading}
              rows={3}
              placeholder="e.g. house, to eat, beautiful, שלום"
              className="w-full rounded-xl border border-slate-200 px-3 py-2.5 text-sm text-slate-800 placeholder-slate-400 focus:outline-none focus:ring-2 focus:ring-sky-500 resize-none disabled:opacity-60 disabled:bg-slate-50"
            />
            <p className="text-right text-xs text-slate-400 mt-1">{words.length}/1000</p>
          </div>

          {error && (
            <div className="rounded-xl bg-red-50 border border-red-200 px-4 py-3 text-sm text-red-700">
              {error}
            </div>
          )}

          <button
            type="submit"
            disabled={loading || !topic.trim()}
            className="w-full flex items-center justify-center gap-2 px-4 py-3 bg-sky-600 hover:bg-sky-700 text-white font-semibold rounded-xl transition-colors shadow-sm disabled:opacity-50 disabled:cursor-not-allowed"
          >
            {loading ? (
              <>
                <div className="animate-spin rounded-full h-4 w-4 border-b-2 border-white" />
                <span>Generating your lesson…</span>
              </>
            ) : (
              <>
                <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M13 10V3L4 14h7v7l9-11h-7z" />
                </svg>
                Generate Lesson
              </>
            )}
          </button>
        </form>
      </div>
    </section>
  );
}
